"""empty message

Revision ID: 4e3764d19625
Revises: cf7fc206c5f1
Create Date: 2021-05-04 01:40:09.589969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3764d19625'
down_revision = 'cf7fc206c5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userJobs', sa.Column('status', sa.String(length=50), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userJobs', 'status')
    # ### end Alembic commands ###
