"""empty message

Revision ID: 768c7b03fc66
Revises: ae5d53121910
Create Date: 2021-04-17 11:23:07.533256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768c7b03fc66'
down_revision = 'ae5d53121910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dummy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dummy', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
