"""empty message

Revision ID: ae4f679d37e3
Revises: dfb9031c7647
Create Date: 2021-04-17 21:48:05.499815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4f679d37e3'
down_revision = 'dfb9031c7647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userJobs', sa.Column('lastModified', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userJobs', 'lastModified')
    # ### end Alembic commands ###
