"""empty message

Revision ID: ae5d53121910
Revises: e5595457c4d9
Create Date: 2021-04-17 11:05:16.320215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5d53121910'
down_revision = 'e5595457c4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userJobs',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('jobTitle', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('typeOfJob', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('applyBy', sa.Date(), nullable=True),
    sa.Column('starts', sa.Date(), nullable=True),
    sa.Column('ends', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('applicationLocation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userJobs')
    # ### end Alembic commands ###
