"""empty message

Revision ID: bd8559042e26
Revises: 4e3764d19625
Create Date: 2021-05-04 01:42:08.652205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8559042e26'
down_revision = '4e3764d19625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userJobs', sa.Column('status', sa.String(length=50), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userJobs', 'status')
    # ### end Alembic commands ###
