"""empty message

Revision ID: cf7fc206c5f1
Revises: 8297af31c2ba
Create Date: 2021-05-04 01:37:35.705338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7fc206c5f1'
down_revision = '8297af31c2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userJobs', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userJobs', 'status')
    # ### end Alembic commands ###
