"""empty message

Revision ID: de572cc64232
Revises: ae4f679d37e3
Create Date: 2021-04-17 22:35:52.082309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de572cc64232'
down_revision = 'ae4f679d37e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userJobs', sa.Column('endDate', sa.Date(), nullable=True))
    op.add_column('userJobs', sa.Column('lastApplicationDate', sa.Date(), nullable=True))
    op.add_column('userJobs', sa.Column('startDate', sa.Date(), nullable=True))
    op.drop_column('userJobs', 'applyBy')
    op.drop_column('userJobs', 'starts')
    op.drop_column('userJobs', 'ends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userJobs', sa.Column('ends', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('userJobs', sa.Column('starts', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('userJobs', sa.Column('applyBy', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('userJobs', 'startDate')
    op.drop_column('userJobs', 'lastApplicationDate')
    op.drop_column('userJobs', 'endDate')
    # ### end Alembic commands ###
