"""empty message

Revision ID: e5595457c4d9
Revises: 8f262ffd07ca
Create Date: 2021-04-17 02:25:21.775328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5595457c4d9'
down_revision = '8f262ffd07ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dummy', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dummy')
    # ### end Alembic commands ###
